site_name: 18comic- 18漫画每天更新首页
site_author: 18comic
site_description: 18漫画(18comic.com)提供海量正版漫画资源，支持多语言阅读和AI增强功能，按摩 侵犯 r18漫画打造沉浸式二次元体验平台。
theme:
  name: readthedocs
nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Contact: contact.md
